### ISSUE TITLE
Creating an announcement without interests causes an error

### ISSUE THREAD

**Issue by tjmw** [thoughtbot/constable#368] opened 2016-06-24 15:44 UTC
Creating an announcement without any interests results in:

`no function clause matching in String.split/3`

This comes from `extract_interest_names` where we try to split interest names on the `,` character.

**Comment by germsvel** [comment] 2017-09-08 20:04
@tjmw I'm revisiting some issues and trying to see if they're still around. I can't reproduce this. It seems to work just fine. Mind if I close this?

**Comment by tjmw** [comment] 2017-09-12 09:06
Sounds fine to me @germsvel :+1: Thanks for looking into it.

**Closed** 2017-09-12 09:06 UTC
